#!/bin/bash
# Set a standard path, with homebrew support
export PATH="/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"

# Move all files in all the directorys to the root dir
find "$1" -mindepth 2 -type f -print -exec mv {} "$1" \;