# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'Komikan' do
	pod 'WPZipArchive'
	pod 'UnrarKit', '~> 2.6'
	pod 'Alamofire'
end

target 'KomikanTests' do

end

target 'KomikanUITests' do

end

